apiVersion: apps/v1
kind: Deployment
metadata:
  name: jela-io-web
  namespace: prod-jela-io
  labels:
    app.kubernetes.io/name: jela.io
    app.kubernetes.io/managed-by: jela.io
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: jela.io
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jela.io
    spec:
      containers:
        - name: jela-io
          image: "beryju.org/jens/jela.io:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            timeoutSeconds: 5
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 20
            timeoutSeconds: 5
            httpGet:
              path: /
              port: http
